### ISSUE TITLE
TestGUI: obrisati projekat

### ISSUE THREAD

**Issue by dcakarevic** [hill11030/GUITestHipoteza#10]
Problem sa metodom crtanja u ovom projektu je klasa crtanje tacaka sa Point klasom. Point uzima celobrojne koordinate, jer Point klasa predstavlja tacku na Graphics objektu. Da bismo prikazali grafik na celoj povrsini Graphics objekta, morali bismo da skaliramo (zumiranje), sto dovodi do pikselizacije. Stoga, koristimo Plotter klasu, u kojoj razvijamo logiku iscrtavanja.

NAPOMENA 1: Y-osa je obrnuta (raste u negativnom smeru). Koristicemo u Plotter klasi
NAPOMENA 2: Korisne metode Graphics klase

- g.Clear(this.BackColor); _brisanje sadrzaja; ostaje samo boja definisana parametrom_
- TranslateTransform: translacija sadrzaja unutar Graphics objekta

**Comment by hill11030** [comment]
Ne kontam!
Ovaj projekat je prazan.

**Comment by dcakarevic** [comment]
Obrisi projekat TestGUI, jer nam ne koristi ni za sta. U opisu je samo obrazlozenje zasto nam metod koji smo koristili u njemu ne radi posao.

**Comment by hill11030** [comment]
Done
