### ISSUE TITLE
Biblioteka MathToolbox

### ISSUE THREAD

**Issue by dcakarevic** [hill11030/GUITestHipoteza#7]
Kreirati novu biblioteku MathToolbox
- Premestiti GaussianGenerator klasu u ovaj projekat
- Dodati reference na ovu biblioteku u projekte po potrebi

**Comment by hill11030** [comment]
Done!!!

**Comment by dcakarevic** [comment]
U GUITestHipoteza projektu dodaj referencu na projekat MatToolbox, ne na dll. Ne build-uje projekat ako nema MathToolbox.dll na putanji.
